### ISSUE TITLE
Add cake-contrib user on NuGet.org

### ISSUE THREAD

**Issue by gep13** [RLittlesII/Cake.SqlPackage#2]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this for Cake.SqlPackage? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by RLittlesII** [comment]
@gep13 I appreciate the formal request.  I have added cake-contrib as a co-owner of the nuget package.  Only question I have is, license to use the cake image, and how do I create my own snazzy image for this repo?

**Comment by gep13** [comment]
Thank you for adding the cake-contrib user.

We are actually in the process of having a Cake Addin Icon created.  Once that is done, we will be encouraging all Addin Maintainers to use that icon.  So for now, if you could hold off on adding the image, that would be appreciated.

**Comment by RLittlesII** [comment]
That's fine.  I am going to close this issue.  If you require further to do's for cake-contrib, you can re-open this issue.
