### ISSUE TITLE
Add addin to website to allow for automatic documentation

### ISSUE THREAD

**Issue by gep13** [RLittlesII/Cake.SqlPackage#3]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by RLittlesII** [comment]
@gep13 Cake.SqlPackage is now listed on http://cakebuild.net/addins/sql/ 
If your satisfied I am going to close this issue.

**Comment by gep13** [comment]
LGTM! 😄 

Thanks for getting this done!
